# url=jdbc:h2:tcp://localhost:9090/mem:dev
# username=dbuser
# password=letmein
# changelog-file=src/main/resources/db/changelog/db.changelog-master.xml

# url: mongodb://localhost:27017/admin?directConnection=true
# username: amalik
# password: password
# changelog-file: db/changelog/mongo.xml

url=jdbc:postgresql://localhost:5432/postgres
username=postgres
password=secret
changelog-file=db/changelog/db.changelog-master.xml

# url: jdbc:oracle:thin:@cs-oracledb.liquibase.net:1521/PP_DEV
# username: liquibase_user
# password: liquibase_user
# changelog-file=db/changelog/db.changelog-master.xml

liquibase.reports.enabled=false
